let nome = prompt('scrivi il tuo nome')
let cognome = prompt('scrivi il tuo cognome')
let colorePref = prompt("Qual'è il tuo colore preferito?")
let numeroCasuale = Math.floor(Math.random() * 23)
console.log(nome+cognome+colorePref+numeroCasuale)